$install_docker_script = <<SCRIPT
echo Installing Docker...
curl -sSL https://get.docker.com/ | sh
usermod -aG docker ubuntu
sudo systemctl enable docker
SCRIPT


Vagrant.configure('2') do |config|

  vm_box = 'ubuntu/xenial64'

  config.vm.define "docker" do |docker|
    docker.vm.box = vm_box
    docker.vm.synced_folder ".", "/vagrant"
    docker.vm.provision "shell", inline: $install_docker_script, privileged: true
    docker.vm.provider "virtualbox" do |vb|
      vb.name = "docker"
      vb.memory = "1024"
    end
  end
end
